projects:
  CmscAPI:
    schemaPath: app\src\main\graphql\schema.json
    includes:
      - app\src\main\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: otnn7ko4zzhy7hnxhukfdz3lvq
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app\src\main\graphql\com\amazonaws\amplify\generated\graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://u4xtz2cmmrhbrbilsu3zqvkhha.appsync-api.us-east-1.amazonaws.com/graphql
