projects:
  AndroidAPI:
    schemaPath: app\src\main\graphql\schema.json
    includes:
      - user
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app\src\main\graphql\com\amazonaws\amplify\generated\graphql
        graphQLApiId: oalc6qigyjb7nid5vhcrxihqgq
      endpoints:
        prod: >-
          https://jsziylrlgfa4vezbzkodstb3ja.appsync-api.us-east-1.amazonaws.com/graphql
